name: daily_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: 0.7.0
  logger: ^0.6.0
    # uuid
  uuid: 2.0.1
  random_color: 1.0.3
  cloud_firestore: 0.8.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
